### ISSUE TITLE
test: Failing tests on windows

### ISSUE THREAD

**Issue by andriihomiak** [neuro-inc/cookiecutter-neuro-project-barebone#37]
After cookicutter update, tests fail on Windows, ex. [here](https://github.com/neuro-inc/cookiecutter-neuro-project-barebone/runs/6707486392?check_suite_focus=true)

**Comment by YevheniiSemendiak** [comment]
fixed in https://github.com/neuro-inc/cookiecutter-neuro-project-barebone/pull/151
